name = "d"
version = "1.0.0"

[deployment]
permission = "public"
nodes = 1

[build]
dir = "build"
entry = "d_debug.wasm"
command = "npm run build:debug"

[build_release]
dir = "build"
entry = "d.wasm"
command = "npm run build:release"
